### PR TITLE
Reset color after draw command and improve hidding chars for password input

### PR DESCRIPTION
**Pull request by ArekMiszcz**
I had a problem when I was trying to draw smth next to Slab.draw() into render function, because Slab draw command was overwriting my colors. I've realised that draw command not reset its color so I did it into this PR.

### CODE REVIEW

**Comment by flamendless** [comment]
Hi. Are you calling Slab.draw() before or after your own draw codes?

**Comment by ArekMiszcz** [comment]
Hi, before, because I want to set the background image (not color).

**Comment by ArekMiszcz** [comment]
image

**Comment by ArekMiszcz** [comment]
I've also improved hiding chars behind password char because it was working only on unfocus event. It was problematic especially when I wanted to record the screen to show to someone what I've did. After those changes password is always hidden behind password char so there is no risk to share the password.

**Comment by flamendless** [comment]
You should set the color before you draw your background image

**Comment by Miszczu2137** [comment]
But then Slab changing the alfa to the different value which hiding my background as well. Its working like that for select box which changing the alfa for scrollbar.

**Comment by flamendless** [comment]
Are you trying to change the color of the slab widget(s)?

What i meant was do this:

lg.setBackgroundColor
lg.setColor
lg.drawImage

lg.setColor
Slab.Draw

**Comment by flamendless** [comment]
May I ask for more information? (
Either a screenshot or small reproduction of the issue

**Comment by Miszczu2137** [comment]
We can even make a quick call if that works for you :) if not I'll try to send you a movie on discord

**Comment by flamendless** [comment]
Minimal code or love file would be better so i can run it on my machine as well

**Comment by Miszczu2137** [comment]
Ok, I'll do it

**Comment by ArekMiszcz** [comment]
[Here](https://github.com/ArekMiszcz/SlabPlayground/blob/main/slab_colors/main.lua) is the example of this problem. Just clone the Slab into slab_colors directory. You should be able to see black screen and when you hover over scrollbar then background should fade in.

**Comment by flamendless** [comment]
Yeah the issue is you're not calling any love.graphics.setColor anywhere in your love.draw as I've said previously

**Comment by Miszczu2137** [comment]
Hmm, let me check this but do you think that it's a proper behavior that Slab influence on different drawings? Isn't better to pretend by doing this by reset this color?

**Comment by ArekMiszcz** [comment]
And what do you think about the password? If this reset color isn't smth what you would like to implement I can move this password changes into different branch if you like it.

**Comment by flamendless** [comment]
Well the issue is not exclusive to slab at all. but as the user, you should correctly color and draw your stuff.

**Comment by flamendless** [comment]
The password issue should be a different issue/pr

**Comment by ArekMiszcz** [comment]
Ok, so I gonna close this PR and create new one for password issue

**Pull request closed without merging**
